# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d1e84bb87b7380d7064be28eece11b762be642c664d711589639b75523fe36b8f1b3f8f663de47a07d4e5d9ec2056286bbfb9fc6e6eb4503a36ced518fff14f

test:
  secret_key_base: 0dea51b49a90cc641096b004d1db564c6670e9c685640ef6e9121a592812c5f5d9a66aa547c867fef0662382abbd9d9f945f11d27f9e9b3dd145b493eeb8cb6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
